default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ajax-tabs-challenge_development

test:
  <<: *default
  database: ajax-tabs-challenge_test
